name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: ZhuJingLe/ZhuJingLe.github.io@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: ZhuJingLe/ZhuJingLe.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: https://www.xxx.com