name: Run Script on Push  
  
on:  
  push:  
    branches: [ main ]  
  
jobs:  
  run-script:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@main 
    - name: Run your script  
      run: |  
        chmod +x deploy.sh 
        ./deploy.sh
      env:
        ACCESS_TOKEN: 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